phases:
  install:
    runtime-versions:
       nodejs: 18
    commands:
      - echo Install Angular CLI and all node_modules 
      - cd $CODEBUILD_SRC_DIR/frontend/app-for-carclub
      - npm install && npm install -g @angular/cli
build:
    commands:
      - echo Build process started now
      - cd $CODEBUILD_SRC_DIR/frontend/app-for-carclub
      - ng build --configuration=production
post_build:
    commands:
      - echo Build process finished, upload artifacts to S3 bucket
      - cd dist/app-for-carclub
      - ls -la
artifacts:
  base-directory: 'frontend/app-for-carclub/dist*'
  discard-paths: yes
  files:
    - '**/*'  